---
title: "analysis"
author: "Antoine"
date: \`r format(Sys.Date(), "%m %d,%Y")`\
output:
  slidy_presentation: default
---

```{r setup, include=FALSE}
rm(list=ls())

# packages
library(tidyverse)

# options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.height = 6, fig.width = 13, fig.align = "center")
```

```{r loading}

## wd
data_path <- "data/exp8"

## dyn
filename.dyn <- list.files(data_path, 
                       pattern="^[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}.txt")

column.names.dyn <- c(
  # init.params
  "infection.rate",
  "proportion",
  "agregation",
  "proba.overwintering",
  "init.nb.adults",
  "proba.birth",
  # time
  "year",
  "tick",
  # outputs
  "visit.count",
  "dyn.inf",
  "dyn.inf.non.occ",
  "dyn.inf.occ",
  "dyn.adults",
  "tot.inf.cur",
  "dyn.curation")

## totals
filename.totals <- list.files(data_path, 
                              pattern="^totals-[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}.txt")

column.names.totals <- c(
  # par.
  "infection.rate",
  "proportion",
  "agregation",
  # time
  "year",
  # outputs
  "crop.loss.1st",
  "crop.loss",
  "crop.save")

## distribution
filename.arrivals <- list.files(data_path,
                                pattern="^distribution-arrival-[0-9]{1,2}-[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}-[0-9]{1,2}.txt") 
column.names.arrivals <- c(
  # par.
  "proportion",
  "agregation", 
  "infection.rate",
  # time
  "year", 
  "tick", 
  # outputs
  "event",
  "pxcor",
  "pycor",
  "t.pest.alone")
```

## Experiment

- faible taux d'infection : infection tous les 3 ticks
- 1 seul cycle infection - guérison possible par année (pas de 2nde infection)


## Dynamics

```{r dynamics}
data.dyn <- tibble(filename.dyn) %>% 
  # load whole data
  mutate(file_contents = map(filename.dyn, ~ read_delim(file.path(data_path, .), delim = " ", col_names = column.names.dyn))) %>% 
  unnest()%>% 
  # select data we are interested in
  select(- filename.dyn, - proba.birth, -proba.overwintering, - init.nb.adults, - visit.count, - tot.inf.cur, - dyn.curation) %>%   # tot crop patches in the landscape
  mutate(stock.crops = 1089 - floor(1089*proportion/100)) %>% 
  # tick = full landscape without pest control
  mutate(tick.full.th = ceiling(stock.crops/infection.rate)) %>% 
  # total infection fill level in the landscape 
  mutate(fill.level = dyn.inf*100/stock.crops) %>%
  # % of landscape infected patches without predators (adults / juveniles)
  mutate(fill.level.non.occ = dyn.inf.non.occ*100/stock.crops) %>%
  # % of landscape infected crop patches with predators (adults / juveniles)
  mutate(fill.level.occ = dyn.inf.occ*100/stock.crops) %>%
  # numeric -> factor (for ggplot)
  mutate(infection.rate = factor(infection.rate)) %>% 
  mutate(proportion = factor(proportion))

values.for.vline <- data.dyn %>%
  select(infection.rate, proportion, agregation, year, tick.full.th) %>%
  distinct() %>%
  mutate(tick.full.th = tick.full.th + 1621)

data.crop.loss <- tibble(filename.totals) %>% 
  # load whole data
  mutate(file_contents = map(filename.totals, ~ read_delim(file.path(data_path, .), delim = " ", col_names = column.names.totals))) %>% 
  unnest() %>% 
  select(- filename.totals, - crop.loss.1st, - crop.save) %>%
  # crop.loss * 100 pour normaliser en %
  mutate(crop.loss = crop.loss) %>% 
  # tot crop patches in the landscape
  mutate(stock.crops = 1089 - floor(1089*proportion/100)) %>% 
  # normalisation de crop.loss selon le nb de patchs crops dans le paysage
  mutate(norm.crop.loss = crop.loss*100/stock.crops) %>% 
  # numeric -> factor (for ggplot)
  mutate(infection.rate = factor(infection.rate)) %>% 
  mutate(proportion = factor(proportion))


data.dyn %>% 
  # filtre
  filter(year == 10) %>%
  filter(agregation == 1) %>%
  filter(proportion %in% c(10,30,50,70,90)) %>%
  filter(infection.rate %in% c(5,10,15,20)) %>% 
  filter(tick %in% seq(1620, 1769, 1)) %>% 
  # ggplot
  ggplot() + 
  # dynamique du taux de remplissage du paysage par inf. -> courbe
  geom_point(mapping = aes(x = tick, y = fill.level, colour = "fill.level"),
             size = 0.5) + 
  geom_point(mapping = aes(x = tick, y = fill.level.non.occ, colour = "fill.level.non.occ"),
             size = 0.5) + 
  geom_point(mapping = aes(x = tick, y = fill.level.occ, colour = "fill.level.occ"),
             size = 0.5) + 
  # ligne verticale = tick th. auquel le paysage devrait être rempli si pas de contrôle
  geom_vline(data=values.for.vline %>% 
               # same filter than data.dyn
               filter(year == 10) %>%
               filter(agregation == 1) %>%
               filter(proportion %in% c(10,30,50,70,90)) %>%
               filter(infection.rate %in% c(5,10,15,20)) %>% 
               # pour éviter message d'erreur on filtre les valeurs hors limite (x -> tick)
               filter(tick.full.th < 1770),
             aes(xintercept=tick.full.th, colour="tick.full.th"), linetype="dashed", size=1) + 
  # dynamique pests/adults -> courbes
  # geom_point(mapping = aes(x = tick, y = dyn.inf * 100 / 2100, colour = "dyn.inf"),
  #            size = 0.5) + 
  # geom_point(mapping = aes(x = tick, y = dyn.inf.non.occ * 100 / 2100, colour = "dyn.inf.non.occ"),
  #            size = 0.5) + 
  # geom_point(mapping = aes(x = tick, y = dyn.inf.occ * 100 / 2100, colour = "dyn.inf.occ"),
  #            size = 0.5) + 
  geom_point(mapping = aes(x = tick, y = dyn.adults * 100 / (max(dyn.adults)+10), colour = "dyn.adults"),
             size = 0.5) + 
  # crop loss -> segment / point
  geom_segment(data = data.crop.loss %>% 
                 # same filter than data.dyn
                 filter(year == 10) %>%
                 filter(agregation == 1) %>%
                 filter(proportion %in% c(10,30,50,70,90)) %>%
                 filter(infection.rate %in% c(5,10,15,20)),
               mapping = aes(x = 1769 , y = norm.crop.loss, yend= 0, xend = 1769), 
               colour="grey50") +
  geom_point(data = data.crop.loss %>% 
               # same filter than data.dyn
               filter(year == 10) %>%
               filter(agregation == 1) %>%
               filter(proportion %in% c(10,30,50,70,90)) %>%
               filter(infection.rate %in% c(5,10,15,20)),
             aes(x = 1769, y = norm.crop.loss, colour= "crop.loss"), size=3) +
  # x = ticks de l'année 10
  scale_x_continuous(name = expression("Tick"), 
                     breaks = c(1660, 1700, 1740),
                     labels = c("40","80","120"),
                     limits = c(1620, 1769)) + # les ticks qui nous intéressent
  # y = double axe -> à gauche : taux de remplissage / à droite : dyn. pests et adults
  scale_y_continuous(name = expression("Landscape fill level (%)"), 
                     sec.axis = sec_axis(~ . * (max(data.dyn$dyn.adults)+10) / 100 , name = "Dynamics of pests & adults (nb.)"), # right axis
                     limits = c(0, 100)) +
  # legends / axes
  scale_colour_manual(values = c("violet","blue", "orange", "cyan", "grey","red")# , 
                      # labels=c("Norm Crop loss","Nb. adults","Nb. infected crop","Occ","Non occ","Fill level by pests","Tick landsc. full")
                      ) +
  # facets
  facet_grid(infection.rate ~ proportion, labeller = label_both) + 
  # titre
  ggtitle("Dynamics of pests and adults + Taux de remplissage par pests : year 10, LA (1)")


```

## Arrivals

## Crop-loss

```{r crop.loss}

```



